### ISSUE TITLE
Release DJI SDK for Windows

### ISSUE THREAD

**Issue by giggio** [dji-sdk/DJI-Windows-SDK-UWP-Sample#1]
It's been a few months since build and the SDK has not yet been released. What are the plans to release it?

**Comment by teamHelperDrone** [comment]
Yes, i try to contact Dji, but no response and no information about this SDK...
I'm looking for the Beta version or Alpha, but there is nothing about that.... 
Someone has information ???

**Comment by mohansriramakrishna** [comment]
I am also looking for the windows sdk.

**Comment by teamHelperDrone** [comment]
Dji just updated own developer website with new page : https://developer.dji.com/windows-sdk/

I hope we will can test the product very quickly!!

**Comment by Kragrathea** [comment]
If you want a preview,  I have been using this while waiting. 
https://github.com/LaurenNeely/DJI-Windows-SDK-UWP-Sample/tree/44aac3c73b3599c6c323db1f5ee24421fe349b4c/DJIWindowsSDK

**Comment by giggio** [comment]
@Kragrathea thanks! I'll try it until DJI releases an official one.

**Comment by memory125** [comment]
Looks like the released Windows SDK is now the alpha edition. Not sure when the formal edition will be released?

**Comment by Acipenser** [comment]
Are there any updates about the state or even the release date of the SDK?
I plan to work with a DJI drone in my master thesis but for that I’d need Windows SDK support.

**Comment by snakehaihai** [comment]
> https://github.com/dji-sdk/DJI-Windows-SDK-UWP-Sample/issues/2#issuecomment-434135483

**Comment by XietongLU** [comment]
It is online now! plz go to dji dev center.
