### ISSUE TITLE
optimization 

### ISSUE THREAD

**Issue by LiangJy123** [dji-sdk/DJI-Windows-SDK-UWP-Sample#3]
When update the UI  at " VideoSource.Invalidate();" ,the program will wait it. It may be cause a crash. the better way is  when update the picture to UI , there is a judgment to judge the last UI updating completed or not.
------------------------------------------------------------
我遇到一个问题，不过我是用的另一个解析库，在解析265码流的时候，我的CPU是几乎是百分之百，但是码流一直在给视频解析函数传数据，导致有时候callback出图片有时快有事时慢，所以在更新UI的时候，就有问题，程序运行个三分钟就崩溃了。所以这个有个地方可以改一下。
我不await UI 的返回，而是我每次更新时，判断上一次的更新完了没。如果更新完成，我就在更新新的图片到UI上，不然就什么都不做。这样就不会积压很多UI更新的线程了。这样做的另一个好处是，如果视频因为解析的原因导致画面延时的话，延时不会累计，而是慢慢的又同步了。可能是我的电脑比较渣，所以才出现这种问题吧。

-----------------------
MainPageViewModel.cs
----------------------
 if (runProcessTask2 == null || runProcessTask2.Status == Windows.Foundation.AsyncStatus.Completed)
            {
                try
                {

                    runProcessTask2 = Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
                      {
                          try
                          {
                              if (VideoSource == null || VideoSource.PixelWidth != width || VideoSource.PixelHeight != height)
                              {
                                  VideoSource = new WriteableBitmap((int)width, (int)height);
                              }

                              buffer.CopyTo(VideoSource.PixelBuffer);

                              VideoSource.Invalidate();
                          }
                          catch (Exception)
                          {
                          }
                      });
                }
                catch (Exception ex)
                {
                    int x = 1;

                }

            }
            else
            {
                Debug.WriteLine("lost frame = "+ thowawayframecount++);

            }
}

**Comment by XietongLU** [comment]
比较好奇，你使用的是哪个解析库？为什么需要解析 H.265 码流？

**Comment by LiangJy123** [comment]
>           比较好奇，你使用的是哪个解析库？为什么需要解析 H.265 码流？

键误，264
