### ISSUE TITLE
Connectivity to Drone

### ISSUE THREAD

**Issue by tofrye** [dji-sdk/DJI-Windows-SDK-UWP-Sample#4]
Hello,

my question is: How is the Drone connected with the Windows PC for this SDK? If Wifi is used, then probably only the Mavic Air is supported as for example the Mavic 2 uses OcuSync and not standard Wifi?

Or is this SDK meant for a mobile windows device which then should be connected to the DJI remote?

Best rgeards

**Comment by peSHIr** [comment]
Yes, I'm assuming it will only be a wifi connection to the actual controller, which will then still do its normal communication to/from the actual drone and act as a backup manual control option when needed for whatever reason.

Still in the stage of getting all the bits and trying to get a first connection going at all.. (Will be trying with the company Phantom 4 Pro+ now, as my personal Spark is of course in no way supported at all.)

**Comment by HerrickSpencer** [comment]
The current version of the beta SDK supports Mavic Air over WiFi connection and P4Pv2 with USB connection.
